name:  Verify compatibility between consumer and provider

on:
  workflow_dispatch:
    inputs:
      consumer:
        description: 'Name of the consumer'     
        required: true
        default: 'PactCalculator\ iOS\ Client'
      consumerTag:
        description: 'Consumer tag'     
        required: false
        default: 'master'
      providerTag:
        description: 'Provider tag'
        required: false
        default: 'master'    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
    - run: gem install pact_broker-client
    - name: Check pact successfully verified
      run: pact-broker can-i-deploy -b ${{ secrets.PACT_BROKER_HOST }} -k ${{ secrets.PACT_BROKER_TOKEN }} -a CalculationAPI --latest ${{ github.event.inputs.providerTag}} -a ${{ github.event.inputs.consumer}} --latest ${{ github.event.inputs.consumerTag}}
