name:  Verify compatibility between consumer and provider

on:
  workflow_dispatch:
    inputs:
      consumer:
        description: 'Name of the consumer'     
        required: true
        default: 'PactCalculator iOS Client'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check pact successfully verified
      run: cd pact/bin &&  ./pact-broker can-i-deploy -b ${{ secrets.PACT_BROKER_HOST }} -k ${{ secrets.PACT_BROKER_TOKEN }} -a CalculationAPI --latest master -a ${{ github.event.inputs.consumer}} --latest master
