name:  Pact verification triggered by consumer

on:
  repository_dispatch:
    types: [verify_pact]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Determine the branch (first provider tag, if it exists)
      id: branch
      run: if [ ! -z "$PROVIDER_TAGS" -a "$PROVIDER_TAGS" != " " ] ; then echo ::set-output name=provider_branch::$(echo "${PROVIDER_TAGS%%,*}") ; else echo ::set-output name=provider_branch::"master" ; fi
      env: 
        PROVIDER_TAGS: ${{ github.event.client_payload.provider_tags }}
    - name: Checkout branch 
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.branch.outputs.provider_branch }} 
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Verify pact
      run: mvn verify -B -Dpact.verifier.publishResults=true
      env:
        CONSUMER_TAGS: ${{ github.event.client_payload.consumer_tags }}
        PACT_BROKER_HOST: ${{ secrets.PACT_BROKER_HOST }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
