name:  Pact verification triggered by consumer

on:
  repository_dispatch:
    types: [verify_pact]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.provider_tag }}
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Set provider version
      run: echo "PACT_PROVIDER_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-$(git rev-parse --short HEAD)"" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn verify -B
      env:
        CONSUMER_TAGS: ${{ github.event.client_payload.consumer_tags }}
        PACT_BROKER_HOST: ${{ secrets.PACT_BROKER_HOST }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        PACT_ENABLE_PENDING: false
        pact_consumer_version:  ${{ github.event.client_payload.consumer_version }}
        pact_verifier_publish: true
        PACT_PROVIDER_VERSION: ${{ env.PACT_PROVIDER_VERSION }}
