name: Pact provider verification on master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Verify pact
      run: mvn verify -B  -Dpact.verifier.publishResults=true
      env:
        PACT_BROKER_HOST: ${{ secrets.PACT_BROKER_HOST }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
